### ISSUE TITLE
Add initial release

### ISSUE THREAD

**Issue by jonringer** [JoelCourtney/mdbook-kroki-preprocessor#3]
Even a 0.0.1 release would help to establish the evolution of the project, please cut a release :)

**Comment by JoelCourtney** [comment]
Will do. I never ended up needing this project like I thought I would, but since there's interest I'll clean it up and publish sometime this week. Thanks! My checklist:

- [x] Readme and code documentation
- [x] fix versions in Cargo.toml
- [x] Verify and remove warning about excalidraw if not a problem anymore
- [x] configurable endpoint (#1)
- [x] Release

**Comment by JoelCourtney** [comment]
My intent is to only publish to crates.io, and to tag a release on Github, but @blaggacao mentioned using this with `nixpkgs` instead of `cargo install`, and I have no experience with Nix. Will that be sufficient?

**Comment by JoelCourtney** [comment]
I've tagged a release on github and published to crates.io. Please let me know if you need this packaged and released to some other repository.

edit I’m closing the issue but you can reopen it if needed.

**Comment by jonringer** [comment]
I would still say that having the tags on your version control match the releases in crates.io. This should help with long term maintenance, especially when many distros usually carry different versions.

I guess I would call it "release hygiene"
